server:
  port: 8003
spring:
  application:
    name: web-demo
  devtools:
    restart:
      enabled: true #开启热部署

info: #spring-boot-starter-actuator info
  app:
    name: ${spring.application.name}

eureka:
  client:
    fetchRegistry: true #是否从eurekaServer中抓取已有的注册信息，默认为ture，单节点无所谓，集群必须为ture才能配合ribbon使用负载均衡
    register-with-eureka: true #注册进eurekaServer ，默认为ture，单节点无所谓，
#    service-url:
#      defaultZone: http://admin:123456@eureka-8091:8091/eureka/,http://admin:123456@eureka-8092:8092/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true #ip地址注册

management:
  endpoints:
    web:
      exposure:
        include: "*"


env:
  test

feign:
  client:
    default: #fegin name ;default configured all @FeignClient
      connectTimeout: 5000
      readTimeout: 5000
      loggerLevel: FULL #NONE ,BASIC,HEADERS,FULL
  hystrix:
    enabled: true #开启熔断
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true #是否开始超时熔断，如果为false，则熔断机制只在服务不可用时开启（spring-cloud-starter-openfeign中的HystrixCommandProperties默认为true）
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #设置超时熔断时间（spring-cloud-starter-openfeign中的HystrixCommandProperties默认为1000毫秒）
ribbon: #Feign调用默认是使用Ribbon进行负载均衡的，所以我们还需要设置关于Ribbon的超时。
  ReadTimeout: 5000 #单位毫秒
  ConnecTimeout: 5000

logging:
  level:
    com.maidong.webdemo.test: debug