server:
  port: 8003
spring:
  application:
    name: web-demo

info: #spring-boot-starter-actuator info
  app:
    name: ${spring.application.name}

eureka:
  client:
    fetchRegistry: true #是否从eurekaServer中抓取已有的注册信息，默认为ture，单节点无所谓，集群必须为ture才能配合ribbon使用负载均衡
    register-with-eureka: true #注册进eurekaServer ，默认为ture，单节点无所谓，
#    service-url:
#      defaultZone: http://admin:123456@eureka-8091:8091/eureka/,http://admin:123456@eureka-8092:8092/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true #ip地址注册

management:
  endpoints:
    web:
      exposure:
        include: info,health


user:
  name: root
  pwd: 123456