server:
  port: 8091
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    hostname: eureka-8091 #主机名需要配置 hosts
    instance-id: eureka-8091
  server:
    enable-self-preservation: false   #默认为开启，false关闭保护机制，这样可以确保注册中心中不可用的实例被及时的剔除（不推荐）,生产环境中一定要设为ture
  client:
#      fetchRegistry: false #表示自己是注册中心，职责是维护服务，而不是调用服务 单机设置false
#      register-with-eureka: false #不向自己注册 单机设置false
#      service-url:
#        defaultZone: http://admin:123456@eureka-8091:8091/eureka/,http://admin:123456@eureka-8092:8092/eureka/ #使用config discover 需要放着bootstrap中

